DHCP:
  DomainName: international-space-station
  Interface: enp34s0
  StartAddr: 10.0.0.2
  EndAddr: 10.0.0.99
  LeaseTTL: 300
  SubnetMask: 255.255.255.0
  Gateway: 10.0.0.1
  LeaseFile: /var/lib/gatekeeper/leases
  NameServers:
    - 8.8.8.8
    - 1.1.1.1
  ReservedAddresses:
    bc:5f:f4:ac:ea:c4: 10.0.0.100
    00:d8:61:39:b5:6a: 10.0.0.101

Web:
  Address: ":8085"
  HTPasswdFile: ".htpasswd"
  Prometheus: true

DNS:
  UpstreamServers:
    - 8.8.8.8
    - 1.1.1.1
  Interface: enp34s0
  Port: 53
  LocalDomains:
    international-space-station: 10.0.0.2
  BlockLists:
    - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
